Пакет os. Операции с файлами (iter9)
maynagashev/go-metrics pull request #9
Opened 2024-05-01 14:03 UTC by maynagashev

2024-05-02 09:27 UTC, gonozov0 requested changes
Отличная работа 👍
Особенно круто, что расписал все изменения в readme
Описал комментарии по улучшению кода

2024-05-02 09:27 UTC, gonozov0 commented on README.md
> +    - [ ] Агент передавать данные в формате gzip (добавить Content-Encoding: gzip в заголовок запроса и сжать данные).
Это нужно научить делать также в рамках этих итераций, странно что автотесты прошли

2024-05-02 09:27 UTC, gonozov0 commented on cmd/server/flags.go
> +			panic(err)
лучше возвращать ошибку, а логировать и паниковать в main

2024-05-02 09:27 UTC, gonozov0 commented on internal/agent/agent.go
> +		// Go клиент автоматом добавляет заголовок "Accept-Encoding: gzip"
Go клиент так точно не делает, это было бы очень странным поведением, мб у тебя сервер если нет такого заголовка, отдает gzip? По хорошему надо в таком случае отдавать json

2024-05-02 09:27 UTC, gonozov0 commented on internal/contracts/metrics/metrics.go
> +type Metrics struct {
Тут в единственном числе правильнее назвать структуру

2024-05-02 09:27 UTC, gonozov0 commented on internal/contracts/metrics/metrics.go
> +	}
По идее это неправильное состояние структуры, давай лучше сделаем конструктор NewMetric, который будет отдавать Metric и проверять по MType, что передано соответствующее значение, иначе отдавать ошибку

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/app/app.go
> +func (s *Server) IsRestoreEnabled() bool {
на мой взгляд странно, что сервер инкапуслирует 1:1 логику конфига

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/storage/memory/memory.go
> +func New(server *app.Server, log *zap.Logger, options ...interface{}) *MemStorage {
Странно, что для инициализации хранилища тебе нужен сервер, по факту все что тебе нужно - это просто сюда передавать конфиг
Если хочешь использовать инкапсулированные методы IsRestoreEnabled, IsStoreEnabled и т.д., то реализуй их просто у конфига и также вызывай тут

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/handlers/json/update/json_update.go
> +		}
не стоит в хендлер переносить зону ответственности роутера, на какие методы и эндпоинты добавить этот хендлер у тебя описано при инциализации роутера, тут дополнительная проверка ни к чему

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/handlers/json/update/json_update.go
> +	m := metrics.Metrics{}
Лучше продублировать сюда эту структуру, у каждого хендлера может быть свое входное тело запроса, и видеть его рядом с хендлером полезно, чтобы понимать сразу, что при ходит на вход

Аналогично стоит сделать, если хендлер возвращает какую-либо структуру

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/handlers/json/update/json_update.go
> +		encoded, err := json.MarshalIndent(ResponseWithMessage{Message: resMessage}, "", " ")
Indent не стоит делать, чтобы не гонять лишние байты по сети

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/storage/memory/memory.go
> +func (ms *MemStorage) UpdateMetric(metric metrics.Metrics) error {
Лучше сделать разные структуры и методы обновления и получения методов для каждого типа
UpdateGauge
UpdateCounter
GetGauge
GetCounter

Так у тебя будет намного читабельнее и понятнее код, легче будет в дальнейшем рефакторить, т.к. switch и возможные nullable значения в структурах воспринимаются сложнее и могут привести к неочевидным багам в будущем

Старайся всегда по максимуму нормализовать структуры (т.е. разбивать на более мелкие с четкими и строгими типами)

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/storage/memory/memory.go
>  }
Это уже зона отвтетсвенности слоя представления данных (в твоем случае хендлера)
MemStorage ответственнен только за сохранность метрик, лучше получи в хенделе GetMetrics() и там уже преобразовывай их к нужному тебе виду

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/storage/memory/memory.go
> +}
На мой взгляд это не должно быть публичным методом, а частью логики инициализации MemStorage
Т.е. если в New передан путь к файлу, то восстанавливаем значения него

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/storage/memory/memory.go
> +}
Аналогично, как будто бы это тоже не нужно выносить наружу, в New принимаем StoreInterval и спавним горутину или выполняем эту логику при каждом сохранении метрики

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/storage/memory/memory.go
> +}
В целом можешь естественно это не править, у тебя и так кажется все отлично работает, но с точки зрения чистоты кода высказал свое мнение)

2024-05-02 09:27 UTC, gonozov0 commented on internal/server/storage/memory/memory.go
> +}
Аналогично не обязательно править

2024-05-03 04:13 UTC, maynagashev commented on internal/contracts/metrics/metrics.go
> +type Metrics struct {
Согласен, поменял. Множественное число так как в самом задании седьмого инкремента было прописано во множественном числе.
![Screenshot 2024-05-03 at 11 11 00](https://github.com/maynagashev/go-metrics/assets/16742629/5db79c9a-9279-4cd5-918f-53bdef97f593)

2024-05-03 04:31 UTC, maynagashev commented on internal/agent/agent.go
> +		// Go клиент автоматом добавляет заголовок "Accept-Encoding: gzip"
Об этом есть информация в теории перед восьмым инкрементом в статье "Оптимизация данных".
![Screenshot 2024-05-03 at 11 26 41](https://github.com/maynagashev/go-metrics/assets/16742629/048b900d-078b-4487-9c19-e6f3ea4d9876)

Также можно косвенно проверить какие клиентские заголовки клиент из пакета net/http отправляет – сделав простой запрос на https://httpbin.org/get и выведя ответ. 

```go
func main() {
	// Отправка GET запроса
	resp, err := http.Get("https://httpbin.org/get")
	if err != nil {
		log.Fatalf("Ошибка при отправке запроса: %v", err)
	}
	defer resp.Body.Close()

	// Чтение тела ответа
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("Ошибка при чтении ответа: %v", err)
	}

	// Отображение тела ответа
	fmt.Println("Ответ от сервера:")
	fmt.Println(string(body))
}
```

Ответ от сервера:
```json
{
  "args": {}, 
  "headers": {
    "Accept-Encoding": "gzip", 
    "Host": "httpbin.org", 
    "User-Agent": "Go-http-client/2.0", 
    "X-Amzn-Trace-Id": "Root=1-663466d2-2f911fac409e14aa45028104"
  }, 
  "origin": "**sensitive**", 
  "url": "https://httpbin.org/get"
}
```

2024-05-03 04:41 UTC, maynagashev commented on internal/agent/agent.go
> +		// Go клиент автоматом добавляет заголовок "Accept-Encoding: gzip"
Явного упоминания в документации пакета http не видать, но есть информация в настройках транспорта, по дефолту у клиента включена поддержка компрессии данных, но ее можно выключить:
```go
	tr := &http.Transport{
		DisableCompression: true,
	}
	client := &http.Client{Transport: tr}

	// Отправка GET запроса
	resp, err := client.Get("https://httpbin.org/get")
```

В таком случае заголовок `Accept-Encoding: gzip` клиент автоматом не отправляет.

2024-05-04 10:47 UTC, maynagashev commented on README.md
> +    - [ ] Агент передавать данные в формате gzip (добавить Content-Encoding: gzip в заголовок запроса и сжать данные).
Добавил сжатие передаваемых данных от агента к серверу.

2024-05-04 11:04 UTC, maynagashev commented on cmd/server/flags.go
> +			panic(err)
Перенес панику в main.

2024-05-05 08:17 UTC, gonozov0 commented on internal/agent/agent.go
> +		// Go клиент автоматом добавляет заголовок "Accept-Encoding: gzip"
Окей, очень интересно конечно, почему решили так сделать по дефолту, большиство клиентов явно не ожидают такого поведения, но отключить легко
В твоем случае тогда без разницы, можешь дефолтное поведение оставить

2024-05-05 08:17 UTC, gonozov0 commented on internal/contracts/metrics/metrics.go
> +type Metrics struct {
Ага, все никак контентщики исправить не могут

2024-05-05 08:24 UTC, gonozov0 requested changes
Отлично поправил, но гитхаб решил скрыть часть моих прошлых комментов, давай их тоже поправим
![image](https://github.com/maynagashev/go-metrics/assets/67286333/100fa127-7e43-4f62-b547-48a35f6aa63f)

2024-05-06 08:13 UTC, gonozov0 approved these changes
Отличная работа 💪

2024-05-11 09:09 UTC, merged